apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-management-api
  labels:
    app: product-management-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-management-api
  template:
    metadata:
      labels:
        app: product-management-api
    spec:
      containers:
        - name: product-management-api
          image: bank20baht/product-management-api:v1.0.3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: ASPNETCORE_HTTP_PORTS
              value: "8080"
            - name: MS_SQL_URL
              value: Server=192.168.1.35,1433;Database=FASME;User Id=SA;Password=B&S#b%1|24?T;TrustServerCertificate=True;
            - name: CORS_ORIGINS
              value: https://product-management-web.20baht.com,http://localhost:4200
