apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-management-web
  labels:
    app: product-management-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-management-web
  template:
    metadata:
      labels:
        app: product-management-web
    spec:
      containers:
        - name: product-management-web
          image: bank20baht/product-management-web:v1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
