apiVersion: v1
kind: Service
metadata:
  name: product-management-web
spec:
  type: ClusterIP
  selector:
    app: product-management-web
  ports:
    - name: http
      port: 80
      targetPort: 80
